  // http://patorjk.com/software/taag/#p=display&f=ANSI%20Shadow&t=YOU%20LOSE!
  DoorWriteLn('[0;40;37m[2J[0;0H');
  DoorWriteLn('');
  DoorWriteLn('');
  DoorWriteLn('');
  DoorWriteLn('');
  DoorWriteLn('');
  DoorWriteLn('');
  DoorWriteLn('');
  DoorWriteLn('[5CллЛ   ллЛ ллллллЛ ллЛ   ллЛ    ллЛ[6CллллллЛ лллллллЛлллллллЛллЛ');
  DoorWriteLn('[5CШллЛ ллЩМллЩЭЭЭллЛллК   ллК    ллК[5CллЩЭЭЭллЛллЩЭЭЭЭМллЩЭЭЭЭМллК');
  DoorWriteLn('[6CШллллЩМ ллК   ллКллК   ллК    ллК[5CллК   ллКлллллллЛлллллЛ  ллК');
  DoorWriteLn('[7CШллЩМ  ллК   ллКллК   ллК    ллК[5CллК   ллКШЭЭЭЭллКллЩЭЭМ  ШЭМ');
  DoorWriteLn('[8CллК   ШллллллЩМШллллллЩМ    лллллллЛШллллллЩМлллллллКлллллллЛллЛ');
  DoorWriteLn('[8CШЭМ    ШЭЭЭЭЭМ  ШЭЭЭЭЭМ[5CШЭЭЭЭЭЭМ ШЭЭЭЭЭМ ШЭЭЭЭЭЭМШЭЭЭЭЭЭМШЭМ');