  // http://patorjk.com/software/taag/#p=display&f=ANSI%20Shadow&t=YOU%20WIN!
  DoorWriteLn('[0;40;37m[2J[0;0H');
  DoorWriteLn('');
  DoorWriteLn('');
  DoorWriteLn('');
  DoorWriteLn('');
  DoorWriteLn('');
  DoorWriteLn('');
  DoorWriteLn('');
  DoorWriteLn('[11C€€ª   €€ª €€€€€€ª €€ª   €€ª    €€ª    €€ª€€ª€€€ª   €€ª€€ª');
  DoorWriteLn('[11C»€€ª €€…º€€…ÕÕÕ€€ª€€∫   €€∫    €€∫    €€∫€€∫€€€€ª  €€∫€€∫');
  DoorWriteLn('[12C»€€€€…º €€∫   €€∫€€∫   €€∫    €€∫ €ª €€∫€€∫€€…€€ª €€∫€€∫');
  DoorWriteLn('[13C»€€…º  €€∫   €€∫€€∫   €€∫    €€∫€€€ª€€∫€€∫€€∫»€€ª€€∫»Õº');
  DoorWriteLn('[14C€€∫   »€€€€€€…º»€€€€€€…º    »€€€…€€€…º€€∫€€∫ »€€€€∫€€ª');
  DoorWriteLn('[14C»Õº    »ÕÕÕÕÕº  »ÕÕÕÕÕº[6C»ÕÕº»ÕÕº »Õº»Õº  »ÕÕÕº»Õº');